Repository DevCycleHQ/ios-client-sdk, pull requests merged in 2023-08, with the labels that each got.

#173 fix: corrected cocoapods publish
  .github/workflows/release.yml
Labels: 1 min review

#174 fix: update cocoapods release to use v-based version
  DevCycle.podspec
Labels: 1 min review

#175 chore: update to use the tagged version of the release action instead of main
  .github/workflows/release.yml
Labels: 1 min review

#176 feat: add apiProxyURL to DevCycleOptions
  DevCycle/DevCycleClient.swift
  DevCycle/Models/DevCycleOptions.swift
  DevCycle/Networking/DevCycleService.swift
  DevCycle/ObjC/ObjCDevCycleOptions.swift
  DevCycleTests/Models/DevCycleOptionsTest.swift
  DevCycleTests/Networking/DevCycleServiceTests.swift
Labels: 5 min review

#177 feat: rename DevCycleOptions.flushEventsIntervalMs to eventFlushIntervalMS
  DevCycle/DevCycleClient.swift
  DevCycle/Models/DevCycleOptions.swift
  DevCycle/ObjC/ObjCDevCycleOptions.swift
  DevCycleTests/Models/DevCycleOptionsTest.swift
Labels: 1 min review

#181 fix: actions worker selecting xcode version
  .github/workflows/ios.yaml
  .github/workflows/macos.yaml
  .github/workflows/tvos.yaml
  .github/workflows/watchos.yaml
Labels: 5 min review

#179 fix: switch DevCycleUser platform params to internal from public
  DevCycle/DevCycleUser.swift
Labels: 1 min review

#180 feat: update variable interface to known supported types
  DevCycle/DVCVariable.swift
  DevCycle/DevCycleClient.swift
  DevCycle/Models/UserConfig.swift
  DevCycle/ObjC/ObjCDVCVariable.swift
  DevCycle/ObjC/ObjCDevCycleClient.swift
  DevCycle/ObjC/ObjCUserConfig.swift
  DevCycleTests/Models/DVCVariableTests.swift
  DevCycleTests/Models/DevCycleClientTests.swift
  DevCycleTests/Models/UserConfigTests.swift
  DevCycleTests/ObjC/ObjCDevCycleClientTests.m
  DevCycleTests/ObjC/ObjcDVCVariableTests.m
Labels: 20 min review
